name: Contagem Regressiva

on:
  push:
    branches: [ index.html ]
  pull_request:
    branches: [ index.html ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: index.html
      run: |
        docker run \ github.com/Alliison/contagemregressiva.io
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
